//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("agendaModel", "aevent_ibfk_1", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.user), "aevent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.aevent), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "aevent_ibfk_2", "location", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.location), "aevent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.aevent), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "comment_ibfk_1", "aevent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.aevent), "comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.comment), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "comment_ibfk_2", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.user), "comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.comment), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "friend_ibfk_1", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.user), "friend", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.friend), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "friend_ibfk_2", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.user), "friend", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.friend), true)]
[assembly: EdmRelationshipAttribute("agendaModel", "location_ibfk_1", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcAgenda.Infrastructure.user), "location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcAgenda.Infrastructure.location), true)]

#endregion

namespace MvcAgenda.Infrastructure
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class agendaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new agendaEntities object using the connection string found in the 'agendaEntities' section of the application configuration file.
        /// </summary>
        public agendaEntities() : base("name=agendaEntities", "agendaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new agendaEntities object.
        /// </summary>
        public agendaEntities(string connectionString) : base(connectionString, "agendaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new agendaEntities object.
        /// </summary>
        public agendaEntities(EntityConnection connection) : base(connection, "agendaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aevent> aevents
        {
            get
            {
                if ((_aevents == null))
                {
                    _aevents = base.CreateObjectSet<aevent>("aevents");
                }
                return _aevents;
            }
        }
        private ObjectSet<aevent> _aevents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comment> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comment>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comment> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<friend> friends
        {
            get
            {
                if ((_friends == null))
                {
                    _friends = base.CreateObjectSet<friend>("friends");
                }
                return _friends;
            }
        }
        private ObjectSet<friend> _friends;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<location> locations
        {
            get
            {
                if ((_locations == null))
                {
                    _locations = base.CreateObjectSet<location>("locations");
                }
                return _locations;
            }
        }
        private ObjectSet<location> _locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aevents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaevents(aevent aevent)
        {
            base.AddObject("aevents", aevent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comment comment)
        {
            base.AddObject("comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the friends EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofriends(friend friend)
        {
            base.AddObject("friends", friend);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolocations(location location)
        {
            base.AddObject("locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agendaModel", Name="aevent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aevent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aevent object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="location_id">Initial value of the location_id property.</param>
        /// <param name="startTime">Initial value of the startTime property.</param>
        public static aevent Createaevent(global::System.Int32 id, global::System.String title, global::System.Int32 location_id, global::System.DateTime startTime)
        {
            aevent aevent = new aevent();
            aevent.id = id;
            aevent.title = title;
            aevent.location_id = location_id;
            aevent.startTime = startTime;
            return aevent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id = 0;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 location_id
        {
            get
            {
                return _location_id;
            }
            set
            {
                Onlocation_idChanging(value);
                ReportPropertyChanging("location_id");
                _location_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("location_id");
                Onlocation_idChanged();
            }
        }
        private global::System.Int32 _location_id;
        partial void Onlocation_idChanging(global::System.Int32 value);
        partial void Onlocation_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startTime
        {
            get
            {
                return _startTime;
            }
            set
            {
                OnstartTimeChanging(value);
                ReportPropertyChanging("startTime");
                _startTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startTime");
                OnstartTimeChanged();
            }
        }
        private global::System.DateTime _startTime;
        partial void OnstartTimeChanging(global::System.DateTime value);
        partial void OnstartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> endTime
        {
            get
            {
                return _endTime;
            }
            set
            {
                OnendTimeChanging(value);
                ReportPropertyChanging("endTime");
                _endTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endTime");
                OnendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _endTime;
        partial void OnendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnendTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "aevent_ibfk_1", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.aevent_ibfk_1", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.aevent_ibfk_1", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.aevent_ibfk_1", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("agendaModel.aevent_ibfk_1", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "aevent_ibfk_2", "location")]
        public location location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<location>("agendaModel.aevent_ibfk_2", "location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<location>("agendaModel.aevent_ibfk_2", "location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<location> locationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<location>("agendaModel.aevent_ibfk_2", "location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<location>("agendaModel.aevent_ibfk_2", "location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "comment_ibfk_1", "comment")]
        public EntityCollection<comment> comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<comment>("agendaModel.comment_ibfk_1", "comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<comment>("agendaModel.comment_ibfk_1", "comment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agendaModel", Name="comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static comment Createcomment(global::System.Int32 id, global::System.String description)
        {
            comment comment = new comment();
            comment.id = id;
            comment.description = description;
            return comment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 event_id
        {
            get
            {
                return _event_id;
            }
            set
            {
                Onevent_idChanging(value);
                ReportPropertyChanging("event_id");
                _event_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("event_id");
                Onevent_idChanged();
            }
        }
        private global::System.Int32 _event_id = 0;
        partial void Onevent_idChanging(global::System.Int32 value);
        partial void Onevent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id = 0;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "comment_ibfk_1", "aevent")]
        public aevent aevent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aevent>("agendaModel.comment_ibfk_1", "aevent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aevent>("agendaModel.comment_ibfk_1", "aevent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aevent> aeventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aevent>("agendaModel.comment_ibfk_1", "aevent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aevent>("agendaModel.comment_ibfk_1", "aevent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "comment_ibfk_2", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.comment_ibfk_2", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.comment_ibfk_2", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.comment_ibfk_2", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("agendaModel.comment_ibfk_2", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agendaModel", Name="friend")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class friend : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new friend object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user1_id">Initial value of the user1_id property.</param>
        /// <param name="user2_id">Initial value of the user2_id property.</param>
        public static friend Createfriend(global::System.Int32 id, global::System.Int32 user1_id, global::System.Int32 user2_id)
        {
            friend friend = new friend();
            friend.id = id;
            friend.user1_id = user1_id;
            friend.user2_id = user2_id;
            return friend;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user1_id
        {
            get
            {
                return _user1_id;
            }
            set
            {
                Onuser1_idChanging(value);
                ReportPropertyChanging("user1_id");
                _user1_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user1_id");
                Onuser1_idChanged();
            }
        }
        private global::System.Int32 _user1_id;
        partial void Onuser1_idChanging(global::System.Int32 value);
        partial void Onuser1_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user2_id
        {
            get
            {
                return _user2_id;
            }
            set
            {
                Onuser2_idChanging(value);
                ReportPropertyChanging("user2_id");
                _user2_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user2_id");
                Onuser2_idChanged();
            }
        }
        private global::System.Int32 _user2_id;
        partial void Onuser2_idChanging(global::System.Int32 value);
        partial void Onuser2_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "friend_ibfk_1", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_1", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_1", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_1", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("agendaModel.friend_ibfk_1", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "friend_ibfk_2", "user")]
        public user user1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_2", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_2", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> user1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.friend_ibfk_2", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("agendaModel.friend_ibfk_2", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agendaModel", Name="location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new location object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="country">Initial value of the country property.</param>
        /// <param name="timezone">Initial value of the timezone property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static location Createlocation(global::System.Int32 id, global::System.String city, global::System.String country, global::System.Int32 timezone, global::System.Int32 user_id)
        {
            location location = new location();
            location.id = id;
            location.city = city;
            location.country = country;
            location.timezone = timezone;
            location.user_id = user_id;
            return location;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 timezone
        {
            get
            {
                return _timezone;
            }
            set
            {
                OntimezoneChanging(value);
                ReportPropertyChanging("timezone");
                _timezone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timezone");
                OntimezoneChanged();
            }
        }
        private global::System.Int32 _timezone;
        partial void OntimezoneChanging(global::System.Int32 value);
        partial void OntimezoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postalcode
        {
            get
            {
                return _postalcode;
            }
            set
            {
                OnpostalcodeChanging(value);
                ReportPropertyChanging("postalcode");
                _postalcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("postalcode");
                OnpostalcodeChanged();
            }
        }
        private global::System.String _postalcode;
        partial void OnpostalcodeChanging(global::System.String value);
        partial void OnpostalcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "aevent_ibfk_2", "aevent")]
        public EntityCollection<aevent> aevents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<aevent>("agendaModel.aevent_ibfk_2", "aevent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<aevent>("agendaModel.aevent_ibfk_2", "aevent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "location_ibfk_1", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.location_ibfk_1", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.location_ibfk_1", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("agendaModel.location_ibfk_1", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("agendaModel.location_ibfk_1", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agendaModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="isAdmin">Initial value of the isAdmin property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String email, global::System.Boolean isAdmin)
        {
            user user = new user();
            user.id = id;
            user.username = username;
            user.password = password;
            user.email = email;
            user.isAdmin = isAdmin;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isAdmin
        {
            get
            {
                return _isAdmin;
            }
            set
            {
                OnisAdminChanging(value);
                ReportPropertyChanging("isAdmin");
                _isAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAdmin");
                OnisAdminChanged();
            }
        }
        private global::System.Boolean _isAdmin;
        partial void OnisAdminChanging(global::System.Boolean value);
        partial void OnisAdminChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "aevent_ibfk_1", "aevent")]
        public EntityCollection<aevent> aevents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<aevent>("agendaModel.aevent_ibfk_1", "aevent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<aevent>("agendaModel.aevent_ibfk_1", "aevent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "comment_ibfk_2", "comment")]
        public EntityCollection<comment> comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<comment>("agendaModel.comment_ibfk_2", "comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<comment>("agendaModel.comment_ibfk_2", "comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "friend_ibfk_1", "friend")]
        public EntityCollection<friend> friends
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<friend>("agendaModel.friend_ibfk_1", "friend");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<friend>("agendaModel.friend_ibfk_1", "friend", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "friend_ibfk_2", "friend")]
        public EntityCollection<friend> friends1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<friend>("agendaModel.friend_ibfk_2", "friend");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<friend>("agendaModel.friend_ibfk_2", "friend", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agendaModel", "location_ibfk_1", "location")]
        public EntityCollection<location> locations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<location>("agendaModel.location_ibfk_1", "location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<location>("agendaModel.location_ibfk_1", "location", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
